site_name: WebMeV User Documentation
site_description: User and how-to guide for WebMeV

repo_url: https://github.com/web-mev/

markdown_extensions:
 - toc:
    anchorlink: True
 - admonition
 - codehilite

theme: readthedocs
extra_css: [extra.css]
nav:
 - Home: 'index.md'
 - Quickstart: 'quickstart.md'
 - Managing files: 'file_management.md'
 - Workspaces: 'workspaces.md'
 - Reproducibility: 'reproducibility.md'
 - "Case study: RNA-Seq": 'rnaseq_case_study.md' 